Repository ISPP-07/frontend-cyc, pull requests merged in 2024-04, with the labels that each got.

#91 Feature/81 food delete edit
  .env.example
  src/app/components/FoodDetails.jsx
  src/app/components/FoodDetailsUpdate.jsx
  src/app/components/FoodDetailsView.jsx
Labels: feature, CyC

#88 feat: emergency button email for CyC
  .env.example
  .gitignore
  next.config.mjs
  package-lock.json
  package.json
  public/icon-192x192.png
  public/icon-256x256.png
  public/icon-384x384.png
  public/icon-512x512.png
  public/manifest.json
  src/app/components/AddElementForm.jsx
  src/app/components/CreateUserForm.jsx
  src/app/components/DeliveriesForm.jsx
  src/app/components/FoodDetails.jsx
  src/app/components/FoodDetailsUpdate.jsx
  src/app/components/FoodDetailsView.jsx
  src/app/components/LoginForm.jsx
  src/app/components/UserDetails.jsx
  src/app/components/WarehouseForm.jsx
  src/app/families/[id]/editFamilyModal.jsx
  src/app/families/[id]/page.jsx
  src/app/families/modal.jsx
  src/app/favicon.ico
  src/app/layout.jsx
  src/app/~offline/page.jsx
  src/pages/api/send-email.js
  src/test/createUserForm.test.js
Labels: feature, CyC

#95 fix: add email sending
  package.json
  src/app/components/LoginForm.jsx
  src/pages/api/send-email.js
Labels: CyC

#101 Feature/100 feat dashboard
  package.json
  public/stats.svg
  src/app/components/DeliveriesForm.jsx
  src/app/components/sidebar.jsx
  src/app/dashboard/Contador.jsx
  src/app/dashboard/page.jsx
Labels: feature
